name: ats CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        run: echo "Build Successful"

  report-of-build:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Build Report
        run: echo "Build Completed Successfully"

  deploy:
    needs: report-of-build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploy Successful"